# -*- coding: utf-8 -*-
"""Strategy abstraction for backtesting.

Inspired by Backtrader's event-driven architecture, this module provides
a pluggable Strategy base class that generates trading signals from
market data context, decoupling strategy logic from the backtest engine.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence

logger = logging.getLogger(__name__)


class SignalType(str, Enum):
    """Trading signal type."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    NO_ACTION = "no_action"


@dataclass
class TradingSignal:
    """A single trading signal generated by a Strategy."""
    signal_type: SignalType = SignalType.HOLD
    strength: float = 0.0  # 0.0-1.0, conviction level
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reasoning: str = ""
    timestamp: Optional[date] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MarketContext:
    """Market data context passed to Strategy.generate_signal().

    Contains all data a strategy needs to make a decision:
    - Daily OHLCV bars (historical)
    - Realtime quote (if available)
    - Technical indicators (if pre-computed)
    - Fundamental data (if available)
    - News context (if available)
    """
    code: str = ""
    current_date: Optional[date] = None
    bars: List[Any] = field(default_factory=list)  # List of DailyBarLike
    realtime_quote: Optional[Dict[str, Any]] = None
    indicators: Dict[str, Any] = field(default_factory=dict)
    fundamentals: Dict[str, Any] = field(default_factory=dict)
    news_context: Optional[str] = None
    position_info: Optional[Dict[str, Any]] = None  # current position if any

    @property
    def latest_bar(self) -> Optional[Any]:
        if self.bars:
            return self.bars[-1]
        return None

    @property
    def latest_close(self) -> Optional[float]:
        bar = self.latest_bar
        if bar and hasattr(bar, 'close') and bar.close is not None:
            return bar.close
        return None


class Strategy(ABC):
    """Abstract base class for trading strategies.

    Subclasses must implement generate_signal().
    Inspired by Backtrader's Strategy.next() but simplified for
    signal generation rather than full order management.
    """

    name: str = "base"
    description: str = ""

    @abstractmethod
    def generate_signal(self, ctx: MarketContext) -> TradingSignal:
        """Generate a trading signal from market context.

        Args:
            ctx: Market data context with bars, indicators, etc.

        Returns:
            TradingSignal with buy/sell/hold recommendation
        """
        ...

    def warmup_period(self) -> int:
        """Number of bars needed before this strategy can generate signals."""
        return 0


class MovingAverageCrossStrategy(Strategy):
    """Simple MA crossover strategy.

    Generates BUY when short MA crosses above long MA,
    SELL when short MA crosses below long MA.
    """

    name = "ma_cross"
    description = "移动平均线交叉策略"

    def __init__(self, short_window: int = 5, long_window: int = 20):
        self.short_window = short_window
        self.long_window = long_window

    def generate_signal(self, ctx: MarketContext) -> TradingSignal:
        bars = ctx.bars
        if len(bars) < self.long_window + 1:
            return TradingSignal(signal_type=SignalType.NO_ACTION, reasoning="数据不足")

        closes = [b.close for b in bars if b.close is not None]
        if len(closes) < self.long_window + 1:
            return TradingSignal(signal_type=SignalType.NO_ACTION, reasoning="收盘价缺失")

        short_ma = sum(closes[-self.short_window:]) / self.short_window
        long_ma = sum(closes[-self.long_window:]) / self.long_window

        # Previous MAs
        prev_short_ma = sum(closes[-self.short_window-1:-1]) / self.short_window
        prev_long_ma = sum(closes[-self.long_window-1:-1]) / self.long_window

        # Crossover detection
        if prev_short_ma <= prev_long_ma and short_ma > long_ma:
            return TradingSignal(
                signal_type=SignalType.BUY,
                strength=0.7,
                reasoning=f"短周期MA({self.short_window})上穿长周期MA({self.long_window})",
                timestamp=ctx.current_date,
            )
        elif prev_short_ma >= prev_long_ma and short_ma < long_ma:
            return TradingSignal(
                signal_type=SignalType.SELL,
                strength=0.7,
                reasoning=f"短周期MA({self.short_window})下穿长周期MA({self.long_window})",
                timestamp=ctx.current_date,
            )
        else:
            return TradingSignal(
                signal_type=SignalType.HOLD,
                reasoning=f"MA未发生交叉，短MA={short_ma:.2f}, 长MA={long_ma:.2f}",
                timestamp=ctx.current_date,
            )

    def warmup_period(self) -> int:
        return self.long_window + 1


class RSIStrategy(Strategy):
    """RSI overbought/oversold strategy."""

    name = "rsi"
    description = "RSI超买超卖策略"

    def __init__(self, period: int = 14, oversold: float = 30.0, overbought: float = 70.0):
        self.period = period
        self.oversold = oversold
        self.overbought = overbought

    def generate_signal(self, ctx: MarketContext) -> TradingSignal:
        bars = ctx.bars
        if len(bars) < self.period + 1:
            return TradingSignal(signal_type=SignalType.NO_ACTION, reasoning="数据不足")

        closes = [b.close for b in bars if b.close is not None]
        if len(closes) < self.period + 1:
            return TradingSignal(signal_type=SignalType.NO_ACTION, reasoning="收盘价缺失")

        # Calculate RSI
        gains = []
        losses = []
        for i in range(1, self.period + 1):
            change = closes[-i] - closes[-i-1]
            if change > 0:
                gains.append(change)
                losses.append(0.0)
            else:
                gains.append(0.0)
                losses.append(abs(change))

        avg_gain = sum(gains) / self.period
        avg_loss = sum(losses) / self.period

        if avg_loss == 0:
            rsi = 100.0
        else:
            rs = avg_gain / avg_loss
            rsi = 100.0 - (100.0 / (1.0 + rs))

        if rsi < self.oversold:
            return TradingSignal(
                signal_type=SignalType.BUY,
                strength=(self.oversold - rsi) / self.oversold,
                reasoning=f"RSI={rsi:.1f}，超卖区域",
                timestamp=ctx.current_date,
            )
        elif rsi > self.overbought:
            return TradingSignal(
                signal_type=SignalType.SELL,
                strength=(rsi - self.overbought) / (100.0 - self.overbought),
                reasoning=f"RSI={rsi:.1f}，超买区域",
                timestamp=ctx.current_date,
            )
        else:
            return TradingSignal(
                signal_type=SignalType.HOLD,
                reasoning=f"RSI={rsi:.1f}，中性区域",
                timestamp=ctx.current_date,
            )

    def warmup_period(self) -> int:
        return self.period + 1


class SignalAggregatorStrategy(Strategy):
    """Meta-strategy that aggregates signals from multiple sub-strategies.

    Runs multiple strategies and combines their signals using weighted voting.
    """

    name = "signal_aggregator"
    description = "多策略信号聚合"

    def __init__(self, strategies: List[Strategy], weights: Optional[List[float]] = None):
        self.strategies = strategies
        if weights and len(weights) == len(strategies):
            self.weights = weights
        else:
            self.weights = [1.0] * len(strategies)

    def generate_signal(self, ctx: MarketContext) -> TradingSignal:
        signals = []
        for strategy in self.strategies:
            try:
                sig = strategy.generate_signal(ctx)
                signals.append((strategy.name, sig))
            except Exception as e:
                logger.warning("[SignalAggregator] strategy %s failed: %s", strategy.name, e)

        if not signals:
            return TradingSignal(signal_type=SignalType.NO_ACTION, reasoning="所有策略均失败")

        # Weighted voting
        buy_score = 0.0
        sell_score = 0.0
        hold_score = 0.0
        reasons = []

        for (name, sig), weight in zip(signals, self.weights):
            reasons.append(f"[{name}] {sig.reasoning}")
            if sig.signal_type == SignalType.BUY:
                buy_score += weight * sig.strength
            elif sig.signal_type == SignalType.SELL:
                sell_score += weight * sig.strength
            else:
                hold_score += weight

        total = buy_score + sell_score + hold_score
        if total == 0:
            return TradingSignal(signal_type=SignalType.HOLD, reasoning="; ".join(reasons))

        if buy_score > sell_score and buy_score > hold_score:
            return TradingSignal(
                signal_type=SignalType.BUY,
                strength=buy_score / total,
                reasoning="; ".join(reasons),
                timestamp=ctx.current_date,
            )
        elif sell_score > buy_score and sell_score > hold_score:
            return TradingSignal(
                signal_type=SignalType.SELL,
                strength=sell_score / total,
                reasoning="; ".join(reasons),
                timestamp=ctx.current_date,
            )
        else:
            return TradingSignal(
                signal_type=SignalType.HOLD,
                reasoning="; ".join(reasons),
                timestamp=ctx.current_date,
            )

    def warmup_period(self) -> int:
        return max(s.warmup_period() for s in self.strategies) if self.strategies else 0


# Strategy registry
_STRATEGY_REGISTRY: Dict[str, type[Strategy]] = {}

def register_strategy(cls: type[Strategy]) -> type[Strategy]:
    """Decorator to register a strategy class."""
    _STRATEGY_REGISTRY[cls.name] = cls
    return cls

def get_strategy(name: str, **kwargs) -> Optional[Strategy]:
    """Instantiate a registered strategy by name."""
    cls = _STRATEGY_REGISTRY.get(name)
    if cls is None:
        return None
    return cls(**kwargs)

def list_strategies() -> List[Dict[str, str]]:
    """List all registered strategies."""
    return [{"name": k, "description": v.description} for k, v in _STRATEGY_REGISTRY.items()]

# Register built-in strategies
register_strategy(MovingAverageCrossStrategy)
register_strategy(RSIStrategy)
register_strategy(SignalAggregatorStrategy)
